// https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/rest-text-to-speech#get-a-list-of-voices
module.exports = [
    { locale: "en-us", gender: "female", voice: "Jessa-24", code: "Jessa24KRUS", language: "English" },
    { locale: "en-us", gender: "male", voice: "Benjamin", code: "BenjaminRUS", language: "English" },
    { locale: "en-us", gender: "female", voice: "Zira", code: "ZiraRUS", language: "English"},
    { locale: "en-us", gender: "female", voice: "Jessa", code: "JessaRUS", language: "English"},
    { locale: "en-us", gender: "male", voice: "Guy", code: "Guy24kRUS", language: "English" },
    /*
    { locale: "ar-SA", gender: "male", voice: "Naayf", code: "Naayf", language: "Arabic"},
    { locale: "ca-ES", gender: "female", voice: "Herena Catalan", code: "HerenaRUS", language: "Catalan"},
    { locale: "zh-CN", gender: "female", voice: "Huihui (Mainland)", code: "HuihuiRUS", language: "Chinese"},
    { locale: "zh-CN", gender: "mail", voice: "Kangkang, Apollo (Mainland)", code: "Kangkang, Apollo", language: "Chinese"},
    { locale: "zh-HK", gender: "female", voice: "Tracy, Apollo (Hong Kong)", code: "Tracy, Apollo", language: "Chinese"},
    { locale: "zh-HK", gender: "male", voice: "Danny, Apollo (Hong Kong)", code: "Danny, Apollo", language: "Chinese"},
    { locale: "zh-TW", gender: "female", voice: "Yating, Apollo (Taiwan)", code: "Yaiting, Apollo", language: "Chinese"},
    { locale: "zh-TW", gender: "male", voice: "Zhiwei, Apollo (Taiwan)", code: "Zhiwei, Apollo", language: "Chinese"},
    { locale: "hr-HR", gender: "male", voice: "Matej", code: "Matej", language: "Croatian"},
    { locale: "en-IE", gender: "male", voice: "Sean", code: "Sean", language:"English (Irish)"},
    { locale: "fr-FR", gender: "female", voice: "Julie Apollo", code: "Julie, Apollo", language:"French"},
    { locale: "fr-FR", gender: "female", voice: "HortenseRUS", code: "HortenseRUS", language:"French"},
    { locale: "fr-FR", gender: "male", voice: "Paul, Apollo", code: "Paul, Apollo", language:"French"},
    { locale: "de-DE", gender: "female", voice: "Hedda", code: "Hedda", language:"German"},
    { locale: "de-DE", gender: "female", voice: "HeddaRUS", code: "HeddaRUS", language:"German"},
    { locale: "de-DE", gender: "male", voice: "Stefan", code: "Apollo", language:"German"},
    { locale: "el-GR", gender: "male", voice: "Stefanos", code: "Stefanos", language:"Greek"},
    { locale: "he-IL", gender: "male", voice: "Asaf", code: "Asaf", language:"Hebrew"},
    { locale: "hi-IN", gender: "female", voice: "Kalpana, Apollo", code: "Kalpana, Apollo", language:"Hindi"},
    { locale: "hi-IN", gender: "male", voice: "Hemant", code: "Hemant", language:"Hindi"},
    { locale: "it-IT", gender: "female", voice: "LuciaRUS", code: "LuciaRUS", language:"Italian"},
    { locale: "it-IT", gender: "male", voice: "Cosimo, Apollo", code: "Cosimo, Apollo", language:"Italian"},
    { locale: "ja-JP", gender: "male", voice: "Ichiro, Apollo", code: "Ichiro, Apollo", language:"Japanese"},
    { locale: "ja-jp", gender: "female", voice: "HarukaRUS", code: "HarukaRUS", language:"Japanese"},
    { locale: "ko-KR", gender: "female", voice: "HeamiRUS", code: "HeamiRUS", language:"Korean"},
    { locale: "pt-BR", gender: "female", voice: "HeloisaRUS", code: "HeloisaRUS", language:"Portuguese (Brazil)"},
    { locale: "pr-BR", gender: "male", voice: "Daniel, Apollo", code: "Daniel, Apollo", language:"Portuguese (Brazil)"},
    { locale: "pt-PT", gender: "female", voice: " HeliaRUS", code: " HeliaRUS", language:"Portuguese (Portugal)"},
    { locale: "ru-RU", gender: "female", voice: "Irina", code: "Irina", language:"Russian"},
    { locale: "ru-RU", gender: "male", voice: "Pavel", code: "Pavel", language:"Russian"},
    { locale: "ru-RU", gender: "female", voice: "EkaterinaRUS", code: "EkaterinaRUS", language:"Russian"},
    { locale: "es-ES", gender: "female", voice: "Laura, Apollo", code: "Laura, Apollo", language:"Spanish"},
    { locale: "es-ES", gender: "female", voice: "HelenaRUS", code: "HelenaRUS", language:"Spanish"},
    { locale: "es-ES", gender: "male", voice: "Pablo", code: "Pablo", language:"Spanish"},
    { locale: "th-TH", gender: "male", voice: "Pattara", code: "Pattara", language:"Thai"},
    { locale: "tr-TR", gender: "female", voice: "SedaRUS", code: "SedaRUS", language:"Turkish"},
    { locale: "vi-VN", gender: "male", voice: "An", code: "An", language:"Vietnamese"}
    */
];